### ISSUE TITLE
NVIM v0.7.2  `null-ls.lua:37: attempt to call field 'format' (a nil value)` and Choose lsp 

### ISSUE THREAD

**Issue by jokerclay** [josean-dev/dev-environment-files#1]
HI ! Josean , Thank you for your amazing video, I  followed along your video , 
Here are some problems I run into, hope it can inspire you and help others out there with similar problems.
1. **`null-ls.lua:37: attempt to call field 'format' (a nil value)`**
this just  because the version of `NVIM v0.7` and `NVIM v0.8`
you can find it [Here：How do I format files? ](https://github.com/jose-elias-alvarez/null-ls.nvim#how-do-i-format-files)
they said :

> null-ls formatters run when you call vim.lsp.buf.formatting() or vim.lsp.buf.formatting_sync(). If a source supports it, you can run range formatting by visually selecting part of the buffer and calling vim.lsp.buf.range_formatting().
On 0.8, you should use vim.lsp.buf.format (see the help file for usage instructions).

so, I change it as following, and it works 
![fix1](https://user-images.githubusercontent.com/38083660/197404253-2f051025-afd7-45e0-b23e-38623e2c0bf0.png)
<br>

2. **Choose a lsp when save a lua file**
after that , you may run into other problem as following
![fix](https://user-images.githubusercontent.com/38083660/197404372-99548deb-4510-48e8-a975-4e391a66dd3f.png)

I don't really know how to fix it, so I add the following
```
if client.name == "sumneko_lua" then
    client.resolved_capabilities.document_formatting = false
    client.resolved_capabilities.document_range_formatting = false
end
```
Just  disable sumneko_lua, instead of choose `null-ls` or `sumneko_lua` every time
I find it [Here : Avoiding LSP formatting conflicts ](https://github.com/jose-elias-alvarez/null-ls.nvim/wiki/Avoiding-LSP-formatting-conflicts)
 and  [Here : Neovim Select a Language Prompt](https://stackoverflow.com/questions/67550082/neovim-select-a-language-prompt)
 

Again,  your video is  amazing , thx !

**Comment by josean-dev** [comment]
Hey! I really appreciate your feedback, happy to hear you enjoyed the video! Thanks for pointing this out and for the detailed explanation of the issue you ran into with images for what you've encountered. What you've described would definitely fix the issue for previous versions of nvim, though you would have to disable "document_formatting" and "document_range_formatting" for all of the languages you have a null-ls formatter configured, not just "sumneko_lua" (i.e. the "tsserver" as well as I am using prettier with null-ls for formatting here too). This was my original approach, but I decided to make this config specifically for NVIM 0.8 or later and modified things according to the null-ls documentation. Using NVIM 0.8 is a requirement for it to work properly. Is there a particular reason why you are using an earlier version of Neovim?
