### ISSUE TITLE
about Vue

### ISSUE THREAD

**Issue by LauGaHo** [josean-dev/dev-environment-files#10]
Hi, the config can not work in vue and I add volar but still not work in vue project, How can I do?

**Comment by LauGaHo** [comment]
Although I add volar in mason.lua and add some in lspconfig.lua, but still not work.So what should I do?

**Comment by josean-dev** [comment]
Hey! Not sure what might be going wrong here. I would check that Mason actually installed volar properly by opening it up with ":Mason" first. If it is, then to see if the lsp configuration itself is working, I'd open a Vue.js file and do ":LspInfo". I don't work with Vue personally so don't have a lot of insight here to be honest. You can also try "vuels" which could also work for you.

**Comment by LauGaHo** [comment]
OK, I try it soon. Thank you
