### ISSUE TITLE
Cloned the repo and everything work except the icons

### ISSUE THREAD

**Issue by ahmdqader** [josean-dev/dev-environment-files#16]
Cloned the repo and everything work except the icons

**Comment by ahmdqader** [comment]
if  i want the  same configs as found here is there any extra steps beside cloning the configs and load it on init?

**Comment by vishal423** [comment]
You can use [nerd](https://github.com/ryanoasis/nerd-fonts) fonts to fix the icons issue

**Comment by josean-dev** [comment]
I'll add this to the ReadMe for clarification. Configuring a Nerd Font would fix the issue. Thanks guys!
