### ISSUE TITLE
Insert to Normal mode escape delay in tmux

### ISSUE THREAD

**Issue by EdAllonby** [josean-dev/dev-environment-files#17]
Hi Josean, thanks for the great video series and repository. Using your setup, exploring nvim and tmux in more detail, and getting used the the keymaps is a fun experience :)

I noticed that when I'm in a tmux session, open up a file in neovim (`nvim .tmux.conf` for example), and then enter insert mode: When I hit the `<esc>` key to exit from insert mode into normal mode there's a perceivable delay before it switches from insert->normal mode - maybe 500ms to a second? This only seems to happen when I use nvim within a tmux session. Outside of tmux the mode switch is instantaneous.

A bit of searching around showed the following 'official' solution by adding the line `set -sg escape-time 10
` to the .tmux.conf. This did seem to fix the `<esc>` insert->normal delay in my case. However, because this is my first experience with tmux, I might just be hiding an issue rather than fixing it with this tweak - https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed. 

A few questions, I suppose:
* Does this delay occur to others - Maybe my iTerm2 + tmux + vim setup isn't quite right.
* If so, is it just something others deal with? Maybe I'm used to the quick toggling between insert->normal mode
* Or, is this quite a common fix you're aware of? If so, shall we add the line to `.tmux.conf`?

Cheers!
Ed

**Comment by josean-dev** [comment]
Hi Ed!

Thanks for pointing this out. I had not realized this was the case, but testing it out now, it is happening to me as well. I hadn't realized because 9 times out of 10 I use "jk" to exit insert mode and barely use the ESC key. The fix seems suitable to me. I'll add it to the repo.

**Comment by EdAllonby** [comment]
Ahh yes, now I remember the jk remap in your video. Thanks for the quick response, great!
