### ISSUE TITLE
Auto Completion not working

### ISSUE THREAD

**Issue by Benjamin0203** [josean-dev/dev-environment-files#24]
Followed the instruction but it's not working. 
I am on Mac M1 Ventura 
[Link](https://github.com/josean-dev/dev-environment-files/blob/main/.config/nvim/lua/josean/plugins/nvim-cmp.lua)

**Comment by Benjamin0203** [comment]
I restarted the terminal and it worked

**Comment by prosaied** [comment]
Lucky you :) , I also did restart but nothing changed ...
