### ISSUE TITLE
Nvim Python

### ISSUE THREAD

**Issue by nikoloskif** [josean-dev/dev-environment-files#27]
I apologize for writing here. Your step-by-step guide to Nvim setup is great!!! 
Could you tell me what and where to add to Nvim settings for working with Python?

**Comment by lmscunha** [comment]
Hey @nikoloskif, have you tried adding the python LSP in the `lspconfig.lua` and `mason.lua` files?

I installed the `pylsp` listed [here](https://github.com/williamboman/mason-lspconfig.nvim). 

Defining its configs like this:

```
lspconfig["pylsp"].setup({
        capabilities = capabilities,
        on_attach = on_attach,
 })
```
And it's working for me. :)

**Comment by nikoloskif** [comment]
Thank you!:)

**Comment by nikoloskif** [comment]
Hey, @lmscunha .
Thank you:)
