### ISSUE TITLE
Basic autocompletion not working

### ISSUE THREAD

**Issue by jcontonio** [josean-dev/dev-environment-files#29]
Watching here: https://youtu.be/vdn_pKJUda8?t=2494 
I don't see the CMP menu come up in any files after restarting nvim, etc. No errors, but nothing happens.

If I do a `:CmpStatus` I see the following:

```
# unused source names
- buffer
- path
- luasnip
```

Any ideas there? Looking at all the config it looks correct.

**Comment by prosaied** [comment]
Did you fix this issue? 
Cause I am in the same step as you, and can not find any solution

**Comment by jibone** [comment]
Hi, just incase someone was reading this. I had a similar issue, but then it was my mistake. the config
```
sources = cmp.config.sources({
    { name = "luasnip" },
    { name = "buffer" },
    { name = "path" },
  }),
```
I had wrote it as `source` instead of `sources` ... 

Anyway thank you Josean ... the tutorial is great!

**Comment by joshdumoulin** [comment]
Also stuck at the same place with also the same :CmpStatus message. I do have have 'sources' written so that is not the problem.
