### ISSUE TITLE
lsp functions not working 2023

### ISSUE THREAD

**Issue by NykuluzC** [josean-dev/dev-environment-files#34]
<img width="1439" alt="image" src="https://github.com/josean-dev/dev-environment-files/assets/109895517/e01ad55b-2f95-4cf8-97a3-f4447c3c2ec0">

not working gF key while im trying and I cannot directly enter file from preview

<img width="1440" alt="image" src="https://github.com/josean-dev/dev-environment-files/assets/109895517/0d2ad6c3-a989-4d6c-9e67-b4782fe0d04d">

Note: I already copied the repo keymaps.lua to try if it was my error

**Comment by tienlx97** [comment]
@NykuluzC  try

```lua
use({
   "nvimdev/lspsaga.nvim",
   "commit":"b7b4777",
})
```

**Comment by NykuluzC** [comment]
<img width="1439" alt="image" src="https://github.com/josean-dev/dev-environment-files/assets/109895517/82a4d999-b5dd-4719-a6ac-02488ec3fab1">

still have erro

**Comment by tienlx97** [comment]
- This is my config nvim / tmux / fish
- This is newest nvim / lspsaga version (similar ). Maybe it work for you

https://github.com/tienlx97/dotfile-setup

**Comment by NykuluzC** [comment]
already fixed, fixed it by changing the lspsaga config from lsp_finder to just finder

<img width="1142" alt="image" src="https://github.com/josean-dev/dev-environment-files/assets/109895517/176c1d7d-c41e-4b5b-af41-7dc5608b2548">

**Comment by BocanceaIonut** [comment]
Hello! I still have this issue. Lspsaga finder is not working as well, it's stuck in loading state.

**Comment by waleking** [comment]
> already fixed, fixed it by changing the lspsaga config from lsp_finder to just finder
> 
> <img alt="image" width="1142" src="https://user-images.githubusercontent.com/109895517/255880457-176c1d7d-c41e-4b5b-af41-7dc5608b2548.png">

It works for me. Thanks! I think we should add the version information in `plugins-setup.lua`.
