### ISSUE TITLE
cmp path not completing the path

### ISSUE THREAD

**Issue by CtrlAltDelight** [josean-dev/dev-environment-files#37]
It works in your recent video for you, but when I tried it I had to add some code before file paths would auto complete.

I'll make a pull request and link it here.

**Comment by CtrlAltDelight** [comment]
#38 

Submitted a pull request.

**Comment by josean-dev** [comment]
Hmm, not sure why it isn't working for you as is. The cmp sources includes the path and it is working for me. The setup function's sources property should look like this:

```lua
cmp.setup({
    -- sources for autocompletion
    sources = cmp.config.sources({
      { name = "nvim_lsp" },
      { name = "luasnip" }, -- snippets
      { name = "buffer" }, -- text within current buffer
      { name = "path" }, -- file system paths
    })
})
```
