### ISSUE TITLE
how to turn off this light bulb

### ISSUE THREAD

**Issue by oldqin97** [josean-dev/dev-environment-files#4]
<img width="103" alt="image" src="https://user-images.githubusercontent.com/48620148/201041405-dbe6b0cf-113c-4325-9377-fc1f72e95245.png">

**Comment by jeantimex** [comment]
The light bulbs come with LSP Saga, you can disable them in `lspsaga.lua` like so:
```
...
saga.init_lsp_saga({
  ...
  -- disable code action prompt
  code_action_prompt = {
    enable = false,
  },
})
```
Hope that works for you.

**Comment by oldqin97** [comment]
Thank you, This problem has bothered me for days
🤗
