### ISSUE TITLE
tab completion in nvim-cmp not working properly

### ISSUE THREAD

**Issue by apicgg** [josean-dev/dev-environment-files#5]
Do you know why super tab completion is not working properly with nvim-cmp?

**Comment by josean-dev** [comment]
Hey! So I removed this from the config a while back, have been using "<C-j>" and "<C-k>" lately. Not sure how your config looks like. Here's a link to the documentation on how to configure it: https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#super-tab-like-mapping

**Comment by apicgg** [comment]
@josean-dev Thanks for your reply. Now I have also moved to ctrl-j and ctrl-k. The tab completion thing is working in a super weird way with nvim-cmp. Thanks again. :)
