### ISSUE TITLE
context_commnetstring nvim-treesitter module is deprecated. Warning present on first open of a file

### ISSUE THREAD

**Issue by ashvinbondada** [josean-dev/dev-environment-files#51]
Steps to reproduce:

Download repo, and use the Lua folder as your nvim setup. Start nvim, allow for all plugins to install. Then attempt to open a file.

context_commentstring nvim-treesitter module is deprecated, use use require('ts_context_commentstring').setup {} and set vim.g.skip_ts_context_commentstring_module = true to speed up loading instead.
This feature will be removed in ts_context_commentstring version in the future
stack traceback:
        ...-commentstring/lua/ts_context_commentstring/internal.lua:135: in function 'attach'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
        [C]: in function 'nvim_cmd'
        ...brew/Cellar/neovim/0.9.4/share/nvim/runtime/filetype.lua:25: in function <...brew/Cellar/neovim/0.9.4/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        ...brew/Cellar/neovim/0.9.4/share/nvim/runtime/filetype.lua:24: in function <...brew/Cellar/neovim/0.9.4/share/nvim/runtime/filetype.lua:10>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function <vim/_editor.lua:0>
        [C]: in function 'pcall'
        ...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:287: in function 'open_in_new_window'
        ...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:334: in function 'fn'
        ...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:170: in function 'edit'
        ...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:180: in function 'fn'
        ...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:49: in function <...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:46>

**Comment by ashvinbondada** [comment]
Has there been a fix for this yet? If there is a related issue, can you please refer me to that? Thank you!

**Comment by RigottiG** [comment]
I've created a PR fixing this issue, you can get the code before it's merged.

#52

**Comment by ashvinbondada** [comment]
Thank you!
