### ISSUE TITLE
LuaSnip failing to update

### ISSUE THREAD

**Issue by solaSell** [josean-dev/dev-environment-files#54]
I have this error message I fail to resolve while attempting to update LuaSnip:

Failed (1)
LuaSnip 6.77ms vim-cmp fetch failed
Fetching submodule reps/jsregexp
fatal: cannot chdir to '../../../../deps/jsregexp': No such file or directory 
Errors during submodule fetch:
dips/jsregexp

The problem started with the advise I got to delete the directory dips/jsregexp for the LuaSnip updates to work.
When that did not help LuaSnip to update, I re-created the directory dips/jsregexp 

Now I do not know how to resolve the "fetch failed"

**Comment by parthbera** [comment]
I had the same issue. I uninstalled and reinstalled luasnip. The problem went away. I investigated a little bit, it's related to the submodule feature of git. I don't have any experience working with git submodules, so I tried the simplest approach and it worked.

**Comment by parthbera** [comment]
If I remember correctly, I only used the lazy UI to uninstall and reinstall LuaSnip. Try the following steps to restore submodules as required by `HEAD` of parent repo.
```bash
cd <nvim-data>/lazy/LuaSnip
git submodule update
```
Then try lazy UI from nvim as usual. The `git submodule update` should restore the submodules to the proper state. If this doesn't help, try `deinit` followed by `update` as [explained here](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-deinit-f--force--all--ltpathgt82308203).
```bash
git submodule deinit --force .
git submodule update --init --recursive --checkout
```

**Comment by solaSell** [comment]
Thanks for the tips, I'll check them out.

**Comment by solaSell** [comment]
Parthbera:
Thanks. Your tips saved the day!

**Comment by solaSell** [comment]
Parthbera:
Thanks. Your tips saved the day!
