### ISSUE TITLE
ReplaceWithRegister official repo

### ISSUE THREAD

**Issue by ashemedai** [josean-dev/dev-environment-files#6]
Hi Josean,

a friend of mine recommended your video about setting up neovim when we discussing moving from our vim setups to neovim. During your video I noticed you configured ReplaceWithRegister:

https://github.com/josean-dev/dev-environment-files/blob/2a192be20dc5b62a9b1b0e733c516a18f5a9054d/.config/nvim/lua/josean/plugins-setup.lua#L44

As the vim-scripts organisation and scraped scripts was a stopgap solution in the period when most vim scripts were not available on GitHub, it had a purpose. However, since most of the scripts are now on GitHub the scraper has stopped, so you probably want to replace it with the official repository at https://github.com/inkarkat/vim-ReplaceWithRegister to get the latest bug fixes.

**Comment by josean-dev** [comment]
Hey! Thanks a lot for pointing these out, really appreciate it. 
I've fixed it with this recent commit: 3347137010a0862432a1bbc9a78a37e875f82ee8
Thanks again!
