### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by kamalkech** [josean-dev/dev-environment-files#65]
Could not parse linter output due to: Expected value but found invalid token at character 1
   output: Error: No ESLint configuration found in .....

**Comment by galaxyblur** [comment]
Are you using the flat file config for eslint? I get the same error, and I am using flat file config, per eslint's latest standard

**Comment by dan1xk** [comment]
#74

**Comment by kecerud** [comment]
Having same issue, @dan1xk fix doesn't work on my end.

**Comment by dan1xk** [comment]
That's weird 😣, have you tried deleting the nvim data and installing everything again? @kecerud

**Comment by kecerud** [comment]
@dan1xk yup, tried to do clean install but still getting the error.

<img width="1340" alt="Screenshot 2024-06-28 at 09 33 19" src="https://github.com/josean-dev/dev-environment-files/assets/75565018/eea9397f-ad78-4273-be13-b87fdfb0a82b">

**Comment by josean-dev** [comment]
Hey! I believe I've encountered this before. Could you try running: `:!eslint_d stop` and `:!eslint_d start` within Neovim to restart eslint_d and then possibly open and close Neovim? Let me know if that resolves the issue.

**Comment by kecerud** [comment]
@josean-dev this actually fixed the issue, huh weird I thought I already tried it out before commenting but it seems like I haven't.
