### ISSUE TITLE
nvim-tree configuration option changed

### ISSUE THREAD

**Issue by ashemedai** [josean-dev/dev-environment-files#7]
When you set up nvim-tree in your video, you configured options as documented:

https://github.com/josean-dev/dev-environment-files/blob/2a192be20dc5b62a9b1b0e733c516a18f5a9054d/.config/nvim/lua/josean/plugins/nvim-tree.lua#L8

Since a few weeks, that first option is now `vim.g.loaded_netrw = 1`.

Edit: since this issue is about nvim-tree anyway, you also have

https://github.com/josean-dev/dev-environment-files/blob/2a192be20dc5b62a9b1b0e733c516a18f5a9054d/.config/nvim/lua/josean/plugins-setup.lua#L53

It is now officially part of the nvim-tree organisation: https://github.com/nvim-tree/nvim-web-devicons
There is a 301 redirect in place, so it still works.

**Comment by josean-dev** [comment]
Thanks again for letting me know about these as well! Really appreciate it.
Fixed with this recent commit: 3347137010a0862432a1bbc9a78a37e875f82ee8
