### ISSUE TITLE
nvim dev env

### ISSUE THREAD

**Issue by piratx** [josean-dev/dev-environment-files#73]
Just installed your nvim dev env on my fresh Sonoma install on mac.. after starting for the first time and updating/installing all the plugins i bumped into this error..

``smart_open_with_trouble()` is deprecated
```lua
-- Use this:
require("trouble.sources.telescope").open()

-- Instead of:
[mason-lspconfig.nvim] installing pyright
`

Also thanks to anyone said about WezTerm, i can now have a terminal without the oh my zsh env or zprezto.. really nice with just couple of brew install plugins commands!

Thank you!

**Comment by josean-dev** [comment]
Was fixed here: 6614ff76b7975689853f45e6b520c7e8ece9984a
