### ISSUE TITLE
Nvim_tree opens instead of alpha

### ISSUE THREAD

**Issue by LeviLovie** [josean-dev/dev-environment-files#77]
I'm new to nvim so i'm unable to fix it by myself. When I open nvim with your config it opens nvim_tree instead of alpha. I tried following the tutorial, and i tried downloading the config from here, but it still doesn't work. Thank you.

**Comment by LeviLovie** [comment]
I managed to make Alpha open on startup by adding this to the init.lua.
```lua
vim.cmd([[Alpha]])
```
But it doesn't seem to be the right way :(

**Comment by josean-dev** [comment]
Hey! Are you using "nvim" or "nvim ." to open Neovim? If you navigate to the directory you want to work in and then just execute "nvim", you should see alpha. Otherwise, if you specify the directory with "." or some other path, it'll open the tree.

**Comment by LeviLovie** [comment]
Oh, thank you so much!

**Comment by josean-dev** [comment]
Of course!
