### ISSUE TITLE
use own snippets in neovim?

### ISSUE THREAD

**Issue by Volker-H** [josean-dev/dev-environment-files#78]
Thanks for this **amazing** neovim setup. One question, where can I write own snippets for the luasnip plugin? I tried a few ways but no success so far. Has anyone achieved this with this setup?

Here ist what I tried:

in the nvim.cmp.lua I added to the config part:
`require("luasnip.loaders.from_lua").lazy_load({ path = "~/.config/nvim/lua/snippets" })`

and in the dir ./snippets I createt the file all.lua

```
local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("all", {
	s("hello", {
		t('print("hello world")'),
	}),
})
```

Problem is that it's not working - the snippet doesn't show up.

Any help / hints would be much appreciated!

**Comment by alexventuraio** [comment]
I put them in the `~/.config/nvim/after/plugin/custom-luasnips.lua` and it all worked just fine.

**Comment by Volker-H** [comment]
**thank you!!!!!!**
After creating the dir an putting the file in that location it worked! (just wondering why...) from the documentation I understood that its possible to define a path for the scripts. Anyhow, thanks again. - that helped me a lot.
