### ISSUE TITLE
pressing Esc key causing previous text to be pasted in insert mode

### ISSUE THREAD

**Issue by qizeng19** [josean-dev/dev-environment-files#8]
hei, josean, thanks for your vedio, your nvim config is amazing, i like it very much,but there is a issue that i cant't fixed, so i need your help

sometimes i  pressing Esc key causing previous text to be pasted in insert mode,then i must close the nvim tab, open it again, it would be ok.
can you give me some advice?

by the way i use "NVIM v0.8.0" / "react+typescript" / Mac os

**Comment by josean-dev** [comment]
Hey! I honestly haven't encountered this. Not sure why that might be happening on your machine.

**Comment by qizeng19** [comment]
I found the reason ，some confilct with webpack plugin  "eslint-webpack-plugin" ,when i delete this plugin , the nvim become normal. ^ _ ^
